export const styles = {
  goldButton: {
    fontSize: '1.25rem',
    margin: '1rem',
    background: '#ffd700',
    color: '#222',
    border: 'none',
    borderRadius: 8,
    padding: '0.75rem 2rem',
    fontWeight: 'bold',
    cursor: 'pointer',
  },
  awardButton: {
    fontSize: '1.25rem',
    background: '#28a745',
    color: '#fff',
    border: 'none',
    borderRadius: 8,
    padding: '0.75rem 2rem',
    fontWeight: 'bold',
    cursor: 'pointer',
  },
  deductButton: {
    fontSize: '1.25rem',
    background: '#dc3545',
    color: '#fff',
    border: 'none',
    borderRadius: 8,
    padding: '0.75rem 2rem',
    fontWeight: 'bold',
    cursor: 'pointer',
  },
  actionButton: { 
    fontSize: '1.25rem',
    background: '#0077ff', 
    color: '#fff', 
    border: 'none', 
    borderRadius: 8, 
    fontWeight: 'bold', 
    cursor: 'pointer'
},
  playerButton: (selected: boolean) => ({
    fontSize: '2rem',
    padding: '0.5rem 1rem',
    borderRadius: 8,
    border: selected ? '2px solid #ffd700' : '2px solid #888',
    background: selected ? '#333' : '#222',
    color: '#fff',
    cursor: 'pointer',
  }),
  smallButton: (color?: string)=>({
    fontSize: '1rem',
    padding: '0.5rem 1rem',
    borderRadius: 6,
    border: 'none',
    backgroundColor: color || '#fff',
    cursor: 'pointer',
  }),
  playerCard: {
    background: '#333',
    borderRadius: 8,
    padding: '0.5rem 1rem',
    minWidth: 100,
    textAlign: 'center' as const,
    position: 'relative' as const,
    overflow: 'visible' as const,
  },
  playerCardHighlighted: (isPositive: boolean) => ({
    borderRadius: 8,
    padding: '0.5rem 1rem',
    minWidth: 100,
    textAlign: 'center' as const,
    position: 'relative' as const,
    overflow: 'visible' as const,
    background: isPositive ? '#28a74550' : '#dc354550',
    border: `2px solid ${isPositive ? '#28a745' : '#dc3545'}`,
    transition: 'background-color 0.3s ease',
  }),
  scoreAnimation: {
    position: 'absolute' as const,
    top: '-40px',
    left: '50%',
    transform: 'translateX(-50%)',
    fontSize: '2rem',
    fontWeight: 'bold',
    animation: 'scoreChange 2s ease-out',
    pointerEvents: 'none' as const,
    zIndex: 100,
  },
  scoreAnimationPositive: {
    color: '#28a745',
  },
  scoreAnimationNegative: {
    color: '#dc3545',
  },
  playerCountSelect: {
    fontSize: '2rem',
    padding: '0.75rem 1.5rem',
    borderRadius: 8,
    border: '2px solid #ffd700',
    background: '#222',
    color: '#ffd700',
    marginLeft: '1rem',
    fontWeight: 600,
    outline: 'none',
    appearance: 'none',
    minWidth: '5rem',
  },
};